export const robots = [
  {
    "Name": "Lynxmotion (LSS) - 4 DoF Robotic Arm (Kit)",
    "manufacturer": "Lynxmotion",
    "price": "714.94",
    "isAvailable": true,
    "imageUrl": "https://www.robotshop.com/media/catalog/product/cache/image/1350x/9df78eab33525d08d6e5fb8d27136e95/l/y/lynxmotion-smart-servo-lss-articulated-robotic-arm-kit-1_3.jpg",
    "quantity": "40",
    "highlight1": "Lynxmotion (LSS) - 4 DoF Robotic Arm (kit)",
    "highlight2": "Designed for STEM education and hobby robotics",
    "highlight3": "Modular design with aluminum, carbon fiber and G10 parts",
    "highlight4": "Uses Lynxmotion Smart Servo (LSS) motors",
    "highlight5": "Graphical UI: LSS FlowArm software",
    "overview": "The Lynxmotion (LSS) - 4 DoF Robotic Arm (kit) is Lynxmotion’s 6th generation articulated robotic arm. This unassembled version is intended as a hobby / scale version of an industrial robotic arm and is designed around the fully configurable Lynxmotion Smart Servo motors and Lynxmotion Servo Erector Set (SES v2) modular construction system."
},
  {
    "name": "Litter-Robot 3 Automatic Self-Cleaning Litter Box - Beige",
    "manufacturer": "Whisker",
    "price": "499.00",
    "isAvailable": true,
    "imageUrl": "https://www.robotshop.com/media/catalog/product/cache/image/1350x/9df78eab33525d08d6e5fb8d27136e95/l/i/litter-robot-iii-open-air-automatic-self-cleaning-litter-box_1.jpg",
    "quantity": "100",
    "highlight1": "Automatic MoonGlo NiteLite (Blue Led)",
    "highlight2": "Drawer Full Indication",
    "highlight3": "Self-Adjusting Cat Sensor",
    "highlight4": "Large Upward Facing Entry for 'Open Air' Feel",
    "highlight5": "Suitable for cats of all sizes",
    "overview": "Easy Set Up & No Special Receptacles or Expensive Waste Bags. The globe and base unit come fully assembled and are very easy to set up. Just plug it in using the included 15 Volts AC adapter, and add litter, that's all. Say goodbye to those expensive special receptacles or waste bags, the Litter-Robot uses regular kitchen garbage bags."
  },
  {
    "name": "Charmed Labs Pixy 2.1 CMUcam5 Image Sensor",
    "manufacturer": "Charmed Labs",
    "price": "65.90",
    "isAvailable": true,
    "imageUrl": "https://www.robotshop.com/media/catalog/product/cache/image/1350x/9df78eab33525d08d6e5fb8d27136e95/c/h/charmed-labs-pixy-2-cmucam5-image-sensor-3.jpg",
    "quantity": "500",
    "highlight1": "Charmed Labs Pixy 2.1 CMUcam5 Image Sensor",
    "highlight2": "Smaller and faster (60 frames per second) than the previous version (Pixy1)",
    "highlight3": "New “line following” mode with custom algorithms for detecting and tracking lines",
    "highlight4": "Improved PixyMon software (PC/Mac/Linux application)",
    "highlight5": "use it wisely!",
    "overview": "Easy Set Up & No Special Receptacles or Expensive Waste Bags. The globe and base unit come fully assembled and are very easy to set up. Just plug it in using the included 15 Volts AC adapter, and add litter, that's all. Say goodbye to those expensive special receptacles or waste bags, the Litter-Robot uses regular kitchen garbage bags."
  },
  {
    "name": "EZ-Robot JD Humanoid Robot",
    "manufacturer": "EZ-Robot",
    "price": "549.99",
    "isAvailable": true,
    "imageUrl": "https://www.robotshop.com/media/catalog/product/cache/image/1350x/9df78eab33525d08d6e5fb8d27136e95/e/z/ez-robot-jd-humanoid-robot.jpg",
    "quantity": "200",
    "highlight1": "Fully functional humanoid robot built with EZ-Bits",
    "highlight2": "Boasts 16 degrees of freedom with 16 heavy duty servos",
    "highlight3": "Camera for vision tracking modes and contains 9 LEDs per eye",
    "highlight4": "Apps to allow him to walk right away",
    "highlight5": "not an overly complicated gift to a 4 year old, trust us!",
    "overview": "The EZ-Robot JD Humanoid Robot is a fully functional humanoid robot built with EZ-Bits. This humanoid boasts 16 degrees of freedom with metal gear heavy duty servo motors. The head of this robot contains a camera for vision tracking modes, including color, motion, glyphs, QR codes and faces. The eyes of this robot have 18 LEDs (9 per eye). Each LED can be configured up to 1 million color combinations. The compact grippers are powered by strong metal geared servo motors. JD includes apps that allows him to walk, right away. Includes digital heavy duty 15 kg/cm servo motors. The metal gear and ball bearing internals will withstand a high load."
},
{
  "name": "Lynxmotion HQuad500 Drone (Base Combo Kit)",
  "manufacturer": "Lynxmotion",
  "price": "419.92",
  "isAvailable": true,
  "imageUrl": "https://www.robotshop.com/media/catalog/product/cache/image/1350x/9df78eab33525d08d6e5fb8d27136e95/l/y/lynxmotion-hquad500-drone-base-combo-kit-1_1.jpg",
  "quantity": "10",
  "highlight1": "HQuad500 Frame and mounting hardware",
  "highlight2": "Includes brushless motors, speed controller and propellers",
  "highlight3": "'Plug and play' for easy solder-less assembly",
  "highlight4": "Requires flight controller, battery, charger and remote (TX/RX)",
  "highlight5": "Incredibly rigid (minimal flexing)",
  "overview": "The Lynxmotion HQuad500 Drone (Base Combo Kit) is a 500mm quadcopter built using the new Lynxmotion M.E.S. (MultiRotor Erector Set) system. The design uses our new aluminum clamps along with 16mm carbon fiber tubes. We equipped the HQuad500 with a camera plate up front which is removable. Different plates will be available as well as a stabilized gimbal system. The flight controller mounting is located at the 'dead center' of the frame with slots accommodating 30.5mm to 45mm mounting. The frame is compatible with the Lynxmotion Quadrino Nano Flight Controller (not included) with a section designed for the GPS antenna and access to the underside ports. There are integrated mounting plates for the ESCs which allow for easy access."
},
{
  "name": "Snapmaker 2.0 Modular 3-in-1 3D Printer A250T",
  "manufacturer": "Snapmaker",
  "price": "1499",
  "isAvailable": true,
  "imageUrl": "https://www.robotshop.com/media/catalog/product/cache/image/1350x/9df78eab33525d08d6e5fb8d27136e95/s/n/snapmaker-20-modular-3-in-1-3d-printer-a250.jpg",
  "quantity": "10",
  "highlight1": "Snapmaker 2.0 Modular 3-in-1 3D Printer A250",
  "highlight2": "Includes 3 Modules: 3D Printing, Laser Cutting and CNC Carving",
  "highlight3": "3D Printing Build Area: 230 x 250 x 235 mm / 9.1 x 9.8 x 9.3 inches",
  "highlight4": "Features a 5-inch 720 x 1280 pixels movable touchscreen",
  "highlight5": "Equipped with a Quad-Core A7 CPU at 1.1 GHz",
  "overview": "The Snapmaker 2.0 Modular 3-in-1 3D Printer A250 is smarter, faster, larger, and more powerful than ever before. It is a new generation of 3-in-1 3D printers that come with everything you need! The A250 offers a 3D Printing Build Volume of 230 x 250 x 235 mm / 9.1 x 9.8 x 9.3 inches, a Laser Engraving and Cutting Work Area of 230 x 250 mm / 9.1 x 9.8 inches and a CNC Carving Work Area of 230 x 250 x 180 mm / 9.1 x 9.8 x 7.5 inches. Ideal for beginners who are just getting started, hobbyists who prefer more customized options, as well as engineers and designers who want to print large objects or accurate parts with outstanding print quality."
},
{
  "name": "Wonder Workshop Dash and Dot Robot Pack (Wonder Pack)",
  "manufacturer": "Wonder Workshop",
  "price": "279.99",
  "isAvailable": true,
  "imageUrl": "https://www.robotshop.com/media/catalog/product/cache/image/1350x/9df78eab33525d08d6e5fb8d27136e95/w/o/wonder-workshop-dash-dot-robot-pack-wonder-pack-v2.jpg",
  "quantity": "60",
  "highlight1": "Pair of robots that combines playing and learning for children",
  "highlight2": "Able to sense their environment and wirelessly programmable",
  "highlight3": "They Move, glow, make sounds and interact with each other",
  "highlight4": "Fully assembled and ready to play",
  "highlight5": "Ages: 8+",
  "overview": "The Wonder Workshop Dash and Dot Robot Pack (Wonder Pack) are capable robots that can sense their environment and can be programmed wirelessly using a touch device. The Dash & Dot are designed to be fun at your home and in a child’s play room. The combination of sensors on these robots, the child friendly programming tools on touch devices, and the design of the robots makes it fun and easy for kids (and grown ups) to do several activities with robots that would have seemed impossible until now. They can move, glow, make sounds and interact with each other. This dynamic duo can do anything you set your mind to."
},
{
  "name": "EZ-Robot JD Humanoid Robot",
  "manufacturer": "EZ-Robot",
  "price": "549.99",
  "isAvailable": true,
  "imageUrl": "https://www.robotshop.com/media/catalog/product/cache/image/1350x/9df78eab33525d08d6e5fb8d27136e95/e/z/ez-robot-jd-humanoid-robot.jpg",
  "quantity": "200",
  "highlight1": "Fully functional humanoid robot built with EZ-Bits",
  "highlight2": "Boasts 16 degrees of freedom with 16 heavy duty servos",
  "highlight3": "Camera for vision tracking modes and contains 9 LEDs per eye",
  "highlight4": "Apps to allow him to walk right away",
  "highlight5": "not an overly complicated gift to a 4 year old, trust us!",
  "overview": "The EZ-Robot JD Humanoid Robot is a fully functional humanoid robot built with EZ-Bits. This humanoid boasts 16 degrees of freedom with metal gear heavy duty servo motors. The head of this robot contains a camera for vision tracking modes, including color, motion, glyphs, QR codes and faces. The eyes of this robot have 18 LEDs (9 per eye). Each LED can be configured up to 1 million color combinations. The compact grippers are powered by strong metal geared servo motors. JD includes apps that allows him to walk, right away. Includes digital heavy duty 15 kg/cm servo motors. The metal gear and ball bearing internals will withstand a high load."
}
]

